export default {
  logo: require('../images/logo.png'),
  TEXT_LOGO: require('../images/textlogo.png'),
  WELCOME1: require('../images/welcome1.png'),
  WELCOME2: require('../images/welcome2.png'),
  WELCOME3: require('../images/welcome3.png'),
  WELCOME4: require('../images/welcome4.png'),
  normal: require('../images/normal.png'),
  gejala: require('../images/gejala.png'),
  stunting: require('../images/stunting.png'),
  laki_laki: require('../images/boys.png'),
  perempuan: require('../images/girls.png'),
  anakStunting: require('../images/anakStunting.png'),
  anakGejala: require('../images/anakGejala.png'),
  anakNormal: require('../images/anakNormal.png'),
  diskominfo: require('../images/diskominfo.png'),
  metromatika: require('../images/metromatika.png'),
  ibuAnak: require('../images/ibuAnak.png'),
  posyandu: require('../images/posyandu.png'),
  penanganan: require('../images/penanganan.png'),
  banner: require('../images/banner.png'),
  logoOTP: require('../images/logoOTP.png'),
};
